### ISSUE TITLE
[AVM Module Issue]: Should be saying permission issue instead of context deadline exceeded.

### ISSUE THREAD

**Issue by VeronicaSea** [Azure/terraform-azurerm-avm-ptn-alz#145]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

1. Run the following code:

module "management_groups" {
  source                = "Azure/avm-ptn-alz/azurerm"
  version               = "v0.10.0"
  parent_resource_id    = local.root_parent_management_group_id
  architecture_name     = local.architecture_name
  location              = local.default_location
  enable_telemetry      = var.enable_telemetry
  policy_default_values = local.default_policy_values
  partner_id            = local.partner_id
  timeouts              = local.management_group_timeouts
  retries               = local.management_group_retries
}

2. Then got the error message "reading Reource: .... : context deadline exceeded".
![Image](https://github.com/user-attachments/assets/889f9d30-8762-4177-8523-b88f8202fb8a)

3. Toggle "On" for "Access management for Azure Resources", this error will be gone.
![Image](https://github.com/user-attachments/assets/7234febe-7c58-406b-8c7d-2a2b2b956a73)

**Comment by matt-FFFFFF** [comment]
Hi @VeronicaSea 

This is by design. As you can see there is a retry set for management groups.

https://github.com/Azure/terraform-azurerm-avm-ptn-alz/blob/main/variables.tf#L172

This is to ensure we get a reliable apply. Sometimes when we create a child management group soon after its parent, this error can occur.

If we can be more specific about the error message detail then we might be able to improve matters.

Please feel free to suggest something.

**Comment by matt-FFFFFF** [comment]
#RR
